"""Antlr generated files.

Files in this package (other than package structure and __init__.py files)
are automatically generated by antlr and should not be edited. Generated files
are committed only to ensure consistency with the antlr runtime specified in
Pipfile.lock an various platforms.
"""
